### ISSUE TITLE
custom gitIgnoreFile option does not work

### ISSUE THREAD

**Issue by L1lith** [standard/deglob#18] opened 2020-04-12 23:09 UTC
**What version of this package are you using?**
4.0.1
**What operating system, Node.js, and npm version?**
Windows 10, Node v12.14.1, NPM v6.13.4
**What happened?**
I passed the following options to the library
```
{
    cwd: targetFolder,
    ignore: ['/node_modules/'],
    useGitIgnore: true,
    usePackageJson: false,
    gitIgnoreFile: '.emignore'
  }
```
However when copying the target directory it completely ignored the rules set in my .emignore file, and copied the source.txt file anyways.
Target Directory Structure
```
source.txt
.emignore
```
.emignore file content
```
source.txt
```
**What did you expect to happen?**
I expected the rules in the .emignore to be respected but they were ignored
**Are you willing to submit a pull request to fix this bug?**
If the author is unwilling to, possibly

**Comment by L1lith** [comment] 2020-04-12 23:34
I solved the problem by implementing the "ignore-walk" library instead, in case anyone needs a solution until this is patched

**Comment by feross** [comment] 2020-10-28 23:36
It's not clear what the cause of this issue is, and we're not using this package in standard anymore, so this issue won't be fixed.

**Closed as completed by feross** 2020-10-28 23:36 UTC
